# Sources definition
SRC_CXX_DIR = ./src

SRC_CXX = schd_trace.cpp \
          simd_trace_map_simvision.cpp \
          simd_trace_map_gtkwave.cpp

-include $(PROJ_ROOT_DIR)/tools/makefile.in
